---
# https://github.com/marketplace/actions/super-linter#supported-linters
# https://github.com/DavidAnson/markdownlint#optionsconfig

MD013: false # https://github.com/DavidAnson/markdownlint/blob/main/doc/md013.md
MD031: false # https://github.com/DavidAnson/markdownlint/blob/main/doc/md031.md
MD047: false # https://github.com/DavidAnson/markdownlint/blob/main/doc/md047.md
...