---
# https://github.com/marketplace/actions/super-linter#supported-linters
# https://github.com/DavidAnson/markdownlint#optionsconfig

# https://github.com/DavidAnson/markdownlint/blob/main/doc/md013.md
MD013: false
...