---
name: keepalive.test

on:
  push:
    branches: [master, main]
    paths: [".github/workflows/keepalive.*"]
  workflow_dispatch:

jobs:
  calling:
    permissions:
      contents: write
    uses: ./.github/workflows/keepalive.yml
