---
name: superlinter.test

concurrency:
  group: ${{ github.workflow }}@${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [master, main]
    paths: ['.github/workflows/superlinter.*']
  workflow_dispatch:

jobs:
  calling:
    permissions:
      contents: read
      packages: read
      statuses: write
    uses: ./.github/workflows/superlinter.yml
...